### ISSUE TITLE
No Idea how to run Robinson

### ISSUE THREAD

**Issue by Wayne-Steele** [aaron-santos/robinson#1]
I have downloaded the zip file from your web site. I figured out that "lein run" might mean I have to install Leiningen, which I then did.  Still no luck.

I've never used clojure, and I haven't done any java development in at least a decade. Please meet me halfway, and give me some guidance on how to run the thing.

**Comment by aaron-santos** [comment]
Hi. Thank you for downloading Robinson.

The zip contains an executable jar file named robinson.jar. Try double-clicking on the jar. Behind the scenes the OS will open it using java and you should be set. Since you've downloaded and installed lein, I believe you should have the java runtime installed which is the only prerequisite for running Robinson.

Lein run is used when running from source. Which brings up a good point - I need to update the README file.

If you have more difficulties please let me know. I'm sure we can work something out :)

**Comment by Wayne-Steele** [comment]
Wow - so prompt!
Actually, I found the problem: Don't use the July release. Use the 2015.09.22 release.
